package bzh.amzerin.openD6.bo;

public enum Keyword {

	ACTION,
	ACTION_LIBRE,
	ATTRIBUT_PAR_DEFAUT,
	CODE_DE,
	COMPETENCE_COMPLEMENTAIRE,
	D,
	DE_LIBRE,
	DIFFICULTE,
	DIFFICULTE_DE_COMBAT,
	DIFFICULTE_STANDART,
	DISTANCE_COMBAT,
	DEGATS_NATURELS,
	DOMMAGE_TOTAL,
	ECHEC_CRITIQUE,
	ECHELLE;
	
}
